### ISSUE TITLE
Programs in web_programming are difficult to write tests for

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/algorithms-keeper#7]
It would be good to have examples of how to mock out network tests.

**Comment by dhruvmanila** [comment]
Do you want the bot to make a comment whenever there is a submission in `web_programming`?

The thing is I don't think it is possible to make it work in `doctest` or if yes, then it might get quite cumbersome. The other alternative is `pytest` or `unittest` (`pytest` is preferred) but most of the users submitting probably don't know about these modules.

Now, if they do know about it then awesome. What a network program does is just two things: make a request and get a response. So, you basically create a mock object or function which gets called when the program makes a request and that returns the response just like a real response would be like. This differs from program to program, sometimes it can be a simple dictionary and other times it would require an object.

What I did in this repository is create a mock `gidgethub.aiohttp.GitHubAPI` object which is in `tests/utils.py` and use that to make the calls, which doesn't actually make any calls but stores what the response is to be given when a certain method is called.

**Comment by dhruvmanila** [comment]
I guess this can be closed as there does not seem to be any need for it. If you feel otherwise, feel free to reopen it.
